// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getAppSettings() : Promise<AppSettings> {
    return await TAURI_INVOKE("get_app_settings");
},
async showMainWindowCommand() : Promise<void> {
    await TAURI_INVOKE("show_main_window_command");
},
async setActivationMode(mode: ActivationMode) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_activation_mode", { mode });
},
async setMuteWhileRecording(enabled: boolean) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_mute_while_recording", { enabled });
},
async setStartHidden(enabled: boolean) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_start_hidden", { enabled });
},
async setAutostart(enabled: boolean) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_autostart", { enabled });
},
async setShowTrayIcon(enabled: boolean) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_show_tray_icon", { enabled });
},
async setRemoveFillerWords(enabled: boolean) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_remove_filler_words", { enabled });
},
async setAppLanguage(language: AppLanguage) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_app_language", { language });
},
/**
 * Clean and Reformat can only be turned on once a Groq key is saved.
 */
async setCleanAndReformat(enabled: boolean) : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clean_and_reformat", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCustomWords(words: string[]) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_custom_words", { words });
},
async setReplacements(replacements: Replacement[]) : Promise<AppSettings> {
    return await TAURI_INVOKE("set_replacements", { replacements });
},
async setGroqApiKey(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_groq_api_key", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasGroqApiKey() : Promise<boolean> {
    return await TAURI_INVOKE("has_groq_api_key");
},
/**
 * Removing the key also turns Clean and Reformat off.
 */
async clearGroqApiKey() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_groq_api_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
settingsChanged: SettingsChanged
}>({
settingsChanged: "settings-changed"
})

/** user-defined constants **/



/** user-defined types **/

export type ActivationMode = "hold" | "toggle"
export type AppLanguage = "en" | "vi"
export type AppSettings = { onboarding_complete: boolean; shortcut: string; activation_mode: ActivationMode; 
/**
 * Microphone name; `None` follows the system default input.
 */
selected_microphone: string | null; 
/**
 * Zero-based input channel; `None` mixes all channels down to mono.
 */
selected_channel: number | null; mute_while_recording: boolean; start_hidden: boolean; autostart_enabled: boolean; show_tray_icon: boolean; remove_filler_words: boolean; app_language: AppLanguage; clean_and_reformat: boolean; custom_words: string[]; replacements: Replacement[] }
export type Replacement = { trigger: string; value: string }
/**
 * Emitted with the full settings after every change. The overlay webview
 * uses it to follow the interface language live.
 */
export type SettingsChanged = AppSettings

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
